### ISSUE TITLE
Audit and summary logs for auzre gov log analytics workspace

### ISSUE THREAD

**Issue by jayhaddad** [Azure/missionlz#1045]
Investigate if audit and summary logs should be offered for log analytics workspaces in azure gov.

**Comment by jamasten** [comment]
The Audit category on the diagnostic setting for the log analytics workspace has been deploying successfully for 3 years now against AzureUSGovernment without an issue. In the past there was a "supportedClouds" param that determined if the diagnostic setting should deploy but that array always included AzureUSGovernment. This leads me to believe a bug fix was added to the API version in AzureUSGovernment preventing the deployment since the Audit category is not supported.
