### ISSUE TITLE
Containers missing environment variable required for air-gapped environments

### ISSUE THREAD

**Issue by Phydeauxman** [Azure/missionlz#224]
**Description**

In air-gapped environments the endpoints for the environment are discovered via the ARM_CLOUD_METADATA_URL variable. This variable assignment is missing from the container definition.

**Steps to Reproduce**
1. Create instance from container image in air-gapped cloud

**Expected behavior**
The container would be able to run Azure CLI commands against the target cloud

**Actual behavior**
When Azure CLI commands are issued, it does not recognize the target cloud

**Screenshots**

**Additional context**
Operating System: Ubuntu 20.04
Terraform Version: NA
Cloud (public, Azure Government, etc.): air-gapped

**Comment by glennmusa** [comment]
@Phydeauxman we currently map that environment value to `MLZ_METADATAHOST` on the container when deploying it, and can probably achieve this by adding the `ARM_CLOUD_METADATA_URL` value to it too:

https://github.com/Azure/missionlz/blob/main/src/scripts/container-registry/deploy_instance.sh#L59

We could add something like:

```bash
env_vars_args+=("MLZ_METADATAHOST=${mlz_metadatahost}")
env_vars_args+=("ARM_CLOUD_METADATA_URL=${mlz_metadatahost}")
```

**Comment by brooke-hamilton** [comment]
This applies to any container we build for MLZ, so I changed the issue title.

**Comment by glennmusa** [comment]
It looks like the full value we need to assign would be: `https://${resourceManager_url}/metadata/endpoints?api-version=2020-06-01`

Given that an `az cloud show` result returns JSON object like:
```json
> az cloud show
{
  "endpoints": {
    ...
    "management": "https://management.core.windows.net/",
    ...
  }
```

**Comment by jjansen23** [comment]
This issue is resolved by us addressing the challenge, in the README.md file for the Iron Bank container.
When the container is invoked as follows: 

https://repo1.dso.mil/dsop/microsoft/azure/mission-landing-zone/-/blob/development/README.md

Run the following commands:

image_name=<copy_pull_link_from_registry1>
container_name=<name_of_container>
docker run -it -d --name ${container_name} ${image_name}
docker exec -it -e ARM_CLOUD_METADATA_URL=${ARM_CLOUD_METADATA_URL} ${container_name} /bin/bash

Where ARM_CLOUD_METADATA_URL points to the site that is specific to the agc env.
