### ISSUE TITLE
Update getting-started documentation with bicep implementation instructions

### ISSUE THREAD

**Issue by lisamurphy-msft** [Azure/missionlz#431]
**Is your feature request related to a problem? Please describe.**
The current getting started documentation does not contain instructions on how to deploy MLZ using Bicep. 

**Describe the solution you'd like**
Add clear and concise instructions on bicep implementation of MLZ in https://github.com/Azure/missionlz/blob/main/docs/getting-started.md

**Comment by glennmusa** [comment]
I too think we could do with simplifying the documentation. 

It'd be nice if when I landed on the repo I could read maybe a single document, or clicked through just one level-deeper after the 10,000 foot view, and then was presented the quickstart to deploy which flavor of MLZ I wanted.

Related, the tooling required to deploy the solution(s) is now 100% third-party. I don't think we need to point users to the devcontainer as **the** means of deployment anymore and can abstract that from any quickstart docs.

The devcontainer still has value for developing for MLZ, and in GitHub Codespaces, and in air-gapped deployments, but perhaps we can link to that from the quickstart-ish docs instead of requiring it.

+@brooke-hamilton for awareness and ideas

**Comment by brooke-hamilton** [comment]
Created #562 to represent this work.

**Comment by DPirnia** [comment]
There was discussion at the MLZ training days around this topic. Keep the folks in mind who may be starting for the first time deploying something to the cloud as your audience. Thanks!
