### ISSUE TITLE
Add conditional deployments to Bicep

### ISSUE THREAD

**Issue by lisamurphy-msft** [Azure/missionlz#434]
**Is your feature request related to a problem? Please describe.**
Typically bicep deployments without name parameters specified will have naming conflicts upon retry.
As a system integrator, what if I want to re-deploy the same named resources to add an additional field or parameter, the retry logic here is not ideal:
`{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"Conflict\",\r\n            \"message\": \"{\\r\\n  \\\"status\\\": \\\"Failed\\\",\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n    \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n    \\\"details\\\": [\\r\\n      {\\r\\n        \\\"code\\\": \\\"DeploymentFailed\\\",\\r\\n        \\\"message\\\": \\\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\\\",\\r\\n        \\\"details\\\": [\\r\\n          {\\r\\n            \\\"code\\\": \\\"Conflict\\\",\\r\\n            \\\"message\\\": \\\"{\\\\r\\\\n  \\\\\\\"error\\\\\\\": {\\\\r\\\\n    \\\\\\\"code\\\\\\\": \\\\\\\"StorageAccountAlreadyTaken\\\\\\\",\\\\r\\\\n    \\\\\\\"message\\\\\\\": \\\\\\\"The storage account named hublogskuidxlmohg37q is already taken.\\\\\\\"\\\\r\\\\n  }\\\\r\\\\n}\\\"\\r\\n          }\\r\\n        ]\\r\\n      }\\r\\n    ]\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"}]}}
`

**Describe the solution you'd like**
I would like it if we incorporated conditional deployments using Bicep to only create new resources if they don't already exist. 
https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/conditional-resource-deployment

**Comment by shawngib** [comment]
@lisamurphy-msft  I want to add that while conditional deployments may assist a little in this area this is actually a bug in our deployment model not randomizing storage names enough as pointed out in the earlier issue #379. Just to clarify more as to why this happens.  This is a result of Azure Storage Accounts requiring a globally unique name, not just your subscription but the entire domain and because we sees the semi-unique uniqueID from the deployment name, it collides. This will be especially a problem because `az deployment create` does not require a `--name` parameter to run but uses the file name, in this case MLZ. So everyone on our team and in the work who runs it without a unique `--name` parameter will end up trying to create the same storage account name which will fail for lack of uniqueness. 
![image](https://user-images.githubusercontent.com/8386143/136078749-137158b9-21c0-449f-a8f2-a0e0c6672a65.png)

**Comment by brooke-hamilton** [comment]
Closing because this is related to #419 in which we made decisions related to idempotency.
