### ISSUE TITLE
Documentation does not include required resourcePrefix parameter

### ISSUE THREAD

**Issue by lisamurphy-msft** [Azure/missionlz#568]
## Description

When deploying MLZ with the instructions provided, there is indication that there is an additional required parameter: 
```
Please provide string value for 'resourcePrefix' (? for help):
```

## Steps to Reproduce

```
az deployment sub create -n <deployment-name> -l <location> -f mlz.bicep 
```

**Comment by brooke-hamilton** [comment]
@lisamurphy-msft There are references to `resourcePrefix` in these two documents. They were added around the same time as you created this bug, so maybe the weren't in the version you saw when this bug was created. Or is there an additional place we need a reference to `resourcePrefix`?
https://github.com/Azure/missionlz#quickstart
https://github.com/Azure/missionlz/blob/main/src/bicep/README.md#azure-cli

**Comment by lisamurphy-msft** [comment]
I see it in the documentation; https://github.com/Azure/missionlz/blob/main/src/bicep/README.md#Azure-CLI as you previously stated. My contention is that required parameters should be listed in the examples as a one-liner instead of the additional prompt which is not what would be expected previously. This is a change in the customer experience with the new required parameter.

**Comment by brooke-hamilton** [comment]
The expected result (the fix for this bug) is to add `resourcePrefix` to the command line examples so that the user is not prompted to enter the value after running the deployment command.
