### ISSUE TITLE
Script the creation of the initial tiers and workloads 

### ISSUE THREAD

**Issue by agoodmiller** [Azure/missionlz#594]
**Is your feature request related to a problem? Please describe.**
I am in the process of building out the primary tiers along with multiple workload tiers for a customer and would like to automate the entire process into a single script.  

**Describe the solution you'd like**
I would love to be able to gather all the information for all of the tiers that need to be built. Put the data into one file or location. Then run a single script that will build all of the tiers from the information.

**Describe alternatives you've considered**
I recently built a PowerShell script that will read data from a JSON file and create the primary tiers.  It will then gather the information about the deployment and use that information to build the workload tiers whose build information is also in the JSON file. (I also have a separate script that will also build out just the workload tiers.  this is in case you need to build out more of them after the initial build has been completed) But it's all a bit clunky and can probably be done better.

**Additional context**

**Comment by brooke-hamilton** [comment]
Thank you @agoodmiller for creating this excellent issue! I think this will be highly valuable as a new example in the `src/bicep/examples` folder. I'm closing this issue because I created #597 as a backlog item to represent this work. Please add feedback there and help us set the right acceptance criteria for that issue.
