### ISSUE TITLE
Move and rename `src/build` folder to `scripts`

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/missionlz#610]
## Benefit/Result/Outcome

So that the scripts in the `src/build` folder are not confused with source code that deploys Mission Landing Zone.

## Description

Move the contents of the `src/build` folder to the `.github/workflows` folder because they are used only by the yaml builds. Remove the `delete.sh` script because it is no longer used.

## Acceptance Criteria

- The files in `src/build` are moved to `.github/workflows`, except for `delete.sh` which is ironically deleted.
- All references to the `src/build` path in the yaml files are updated to point to `.github/workflows`.
- The `src/build` folder is removed.
- GitHub Workflows are updated to call the correct path to the relevant script

**Comment by glennmusa** [comment]
Agreed! I think they'd be even better suited to move to where they're used since they're not general purpose:

- .github/workflows/scripts
    - validate_tf
    - check_tf_format.sh

It looks like `src/scripts/delete.sh` is no longer used and can be removed from the repo. The pipelines that used to use now invoke Azure CLI commands directly.

**Comment by brooke-hamilton** [comment]
Based on the 👍 above I updated the acceptance criteria. 😸

**Comment by brooke-hamilton** [comment]
I think we have consensus on this issue so I'm moving it to the current release and removing the triage label.
