### ISSUE TITLE
A Few Remediation Policy examples

### ISSUE THREAD

**Issue by Fatwes** [Azure/missionlz#647]
## Benefit/Result/Outcome

I would like you thank you for this great MLZ, its truly wonderful. If you were to add a few remediation policy examples or policies as code it would be helpful. For example, once NIST 800 compliance is enabled and a resource is shown to be "Non-compliant" because it doesn't have a Log Analytics Agent installed, the remediation task could be triggered to make it compliant. This would serve as an example to built off of for the rest of the items

## Description

Having a few remediation policies for easier Compliance items would be helpful. Then the users could build off these.

## Acceptance Criteria

-  
-

**Comment by brooke-hamilton** [comment]
@Fatwes thank you for the feedback! 🚀 ✨ 

Our approach so far has been to deploy the built-in policy initiatives as optional parts of the deployment. The policies default to notify/warn rather than remediate so that people have a chance to review and make changes to the policies they want to have before turning up full enforcement or remediation.

I think what you are suggesting would make a great add-on or example in the `src/Bicep/examples` folder as an additional deployment after the initial deployment of Mission LZ. Also, it would be good to show how to deploy it to different scopes, i.e., resource group, subscription, and management group. What do you think?

Do you have an existing example you would like to see there? If you develop something along these lines please let us know. 👍

**Comment by brooke-hamilton** [comment]
@Fatwes I'm going to close the issue for now, but if you want to discuss more please add more comments here or start a thread in the [discussions](https://github.com/Azure/missionlz/discussions).
