### ISSUE TITLE
Terraform resource naming to match Bicep resource naming

### ISSUE THREAD

**Issue by lisamurphy-msft** [Azure/missionlz#678]
## Benefit/Result/Outcome

Provide consistent resource naming between Terraform and Bicep so that the Terraform deployment output looks similar to the Bicep deployment.

## Description

The resource names created by Terraform are not consistent with resource names created by the Bicep deployment. We want to make the names as consistent as possible, allowing for differences when Terraform features do not allow the same implementation as Bicep. 

The `resourcePrefix` and `resourceSuffix` parameters should be consistent with Bicep, having `resourcePrefix` as a required parameter.

> NOTE: The Bicep templates have a specific way of implementing naming conventions by using a parameter/variable combination with string replacements. We do not have to implement the same pattern if Terraform makes it difficult. We want the same resource names produced by the template regardless of how it's implemented in Terraform.

## Acceptance Criteria

- The Terraform deployment makes the `resourcePrefix` parameter required. 
- The Terraform deployment uses the `resourcePrefix` and `resourceSuffix` parameters in a way that is consistent with the Bicep deployment.
- Resources created by the Terraform deployment have names consistent with the Bicep deployment, as much as possible.

**Comment by brooke-hamilton** [comment]
The resource prefix parameter in Bicep is used to calculate unique names, using logic that is different than what was implemented in Terraform. The naming conventions are also different between MLZ Bicep and Terraform. Therefore I think that we should consider implementing all of the Bicep naming logic in Terraform rather than just requiring the `resourcePrefix` parameter, which would have small additional value. 

Let's start with #679 to document all of the major differences between the Bicep and Terraform deployments and then decide which things we want to implement in Terraform.

**Comment by brooke-hamilton** [comment]
I updated the title and description.

**Comment by jamasten** [comment]
We will not be updating the terraform code and will be deprecating the terraform code on June 30, 2024.
