### ISSUE TITLE
Unable to use powershell to create output file for tier 3 workload

### ISSUE THREAD

**Issue by LManning-Dev** [Azure/missionlz#715]
On the examples page, I see 2 ways to get the outputs
az deployment sub show -n MLZDeploymentName --query properties.outputs > ./deploymentVariables.json
(Get-AzSubscriptionDeployment -Name MLZDeploymentName).outputs | ConvertTo-Json | Out-File -FilePath .\deploymentVariables.json

The CLI command works well, but the PowerShell does not. 
The output of PowerShell is

"hub":  {
                "Type":  "Object",
                "Value":  [
                              "mysubscriptionId",
                              "myresourcegroupname-rg",
                             "/subscriptions/mysubscriptionId....prefix-vnet-hub-mlz",
                              .... More fields
                          ]
            },

The output of the CLI is

 "hub": {
    "type": "Object",
    "value": {
      "networkSecurityGroupName": "prefix-nsg-hub-suffix",
      "networkSecurityGroupResourceId": "/subscriptions/mysubscriptionID/resourceGroups/.../prefix-nsg-hub-suffix",
      "resourceGroupName": "prefix-rg-hub-suffix",
      ... More Fields
    }
  },

When I used the output from PowerShell to deploy the tier 3 I get 
"The template resource 'hubSubscriptionId' at line '53' and column '30' is not valid." 

When I use the output from the CLI everything works.

Thank you

**Comment by nhwkuhns** [comment]
I believe that the issue here is that the resulting JSON from the PS command does not have a properly configured "hub" object. When you try to read the hubSubscriptionId, hubResourceGroupName, hubVirtualNetworkName, and hubVirtualNetworkResourceId from the JSON created this way you have to use array notation, i.e.,

`param hubSubscriptionId string = mlzDeploymentVariables.hub.Value[0]
param hubResourceGroupName string = mlzDeploymentVariables.hub.Value[1]
param hubVirtualNetworkName string = mlzDeploymentVariables.hub.Value[3]
param hubVirtualNetworkResourceId string = mlzDeploymentVariables.hub.Value[4]`

**Comment by jamasten** [comment]
We are no longer supporting this method and will be using template specs with UI definitions going forward.
